logging:
  level:
    jp:
      cloudnativedays:
        social:
          analysis: INFO
    com:
      slack:
        api: INFO

sentiment:
  file: data/pn.csv.m3.120408.trim

twitter:
  enabled: true
  query: "#hoge"
  # 3min per interval. This should be able to query 500 tweets per min
  interval: 180000

slack:
  enabled: false

wavefront:
  tracing:
    enabled: false
#  freemium-account: false
  application:
    name: social-analyzer
    service: social-analyzer

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
